# Generated by Django 3.1.4 on 2021-07-25 16:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('automation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like_service_purchased', models.BooleanField(default=False)),
                ('comment_service_purchased', models.BooleanField(default=False)),
                ('follower_service_purchased', models.BooleanField(default=False)),
                ('picture_link', models.CharField(max_length=1000)),
                ('number_of_users', models.IntegerField(default=0)),
                ('comment_message', models.CharField(max_length=500)),
                ('amount_of_likes', models.IntegerField(default=0)),
                ('number_of_followers', models.IntegerField(default=0)),
                ('completed', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
