# Generated by Django 3.1.4 on 2021-07-29 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0002_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='account_link',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
